/**
 * Danh sách thủ công cực kỳ đầy đủ, bao gồm hơn 180 ngôn ngữ phổ biến nhất
 * trên thế giới theo chuẩn ISO 639-1.
 * Định dạng: 'Tên bản địa (Tên tiếng Việt)' để cung cấp thông tin tối đa.
 */
const languageLabels = {
  'aa': 'Afaraf (Tiếng Afar)',
  'ab': 'Аҧсуа (Tiếng Abkhazian)',
  'ae': 'Avesta',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'am': 'አማርኛ (Tiếng Amharic)',
  'an': 'Aragonés',
  'ar': 'العربية (Tiếng Ả Rập)',
  'as': 'অসমীয়া (Tiếng Assamese)',
  'av': 'Авар мацӀ (Tiếng Avaric)',
  'ay': 'Aymar aru',
  'az': 'Azərbaycan dili',
  'ba': 'Башҡорт теле (Tiếng Bashkir)',
  'be': 'Беларуская (Tiếng Belarusian)',
  'bg': 'Български език (Tiếng Bulgarian)',
  'bh': 'भोजपुरी',
  'bi': 'Bislama',
  'bm': 'Bamanankan',
  'bn': 'বাংলা (Tiếng Bengali)',
  'bo': 'བོད་ཡིག (Tiếng Tây Tạng)',
  'br': 'Brezhoneg',
  'bs': 'Bosanski jezik',
  'ca': 'Català',
  'ce': 'Нохчийн мотт (Tiếng Chechen)',
  'ch': 'Chamoru',
  'co': 'Corsu',
  'cr': 'ᓀᐦᐃᔭᐍᐏᐣ (Tiếng Cree)',
  'cs': 'Česky (Tiếng Séc)',
  'cu': 'Словѣньскъ ѩзыкъ',
  'cv': 'Чӑваш чӗлхи (Tiếng Chuvash)',
  'cy': 'Cymraeg (Tiếng Wales)',
  'da': 'Dansk (Tiếng Đan Mạch)',
  'de': 'Deutsch (Tiếng Đức)',
  'dv': 'ދިވެހި (Tiếng Divehi)',
  'dz': 'རྫོང་ཁ (Tiếng Dzongkha)',
  'ee': 'Eʋegbe',
  'el': 'Ελληνικά (Tiếng Hy Lạp)',
  'en': 'English (Tiếng Anh)',
  'eo': 'Esperanto (Quốc tế ngữ)',
  'es': 'Español (Tiếng Tây Ban Nha)',
  'et': 'Eesti (Tiếng Estonian)',
  'eu': 'Euskara',
  'fa': 'فارسی (Tiếng Ba Tư)',
  'ff': 'Fulfulde',
  'fi': 'Suomi (Tiếng Phần Lan)',
  'fj': 'Vosa Vakaviti',
  'fo': 'Føroyskt',
  'fr': 'Français (Tiếng Pháp)',
  'fy': 'Frysk',
  'ga': 'Gaeilge (Tiếng Ireland)',
  'gd': 'Gàidhlig',
  'gl': 'Galego',
  'gn': 'Avañe\'ẽ',
  'gu': 'ગુજરાતી (Tiếng Gujarati)',
  'gv': 'Gaelg',
  'ha': 'Hausa',
  'he': 'עברית (Tiếng Hebrew)',
  'hi': 'हिन्दी (Tiếng Hindi)',
  'ho': 'Hiri Motu',
  'hr': 'Hrvatski (Tiếng Croatia)',
  'ht': 'Kreyòl ayisyen',
  'hu': 'Magyar (Tiếng Hungary)',
  'hy': 'Հայերեն (Tiếng Armenian)',
  'hz': 'Otjiherero',
  'ia': 'Interlingua',
  'id': 'Bahasa Indonesia',
  'ie': 'Interlingue',
  'ig': 'Igbo',
  'ii': 'ꆈꌠ꒿ Nuosuhxop',
  'ik': 'Iñupiaq',
  'io': 'Ido',
  'is': 'Íslenska (Tiếng Iceland)',
  'it': 'Italiano (Tiếng Ý)',
  'iu': 'ᐃᓄᒃᑎᑐᑦ (Tiếng Inuktitut)',
  'ja': '日本語 (Tiếng Nhật)',
  'jv': 'Basa Jawa',
  'ka': 'ქართული (Tiếng Georgian)',
  'kg': 'KiKongo',
  'ki': 'Gĩkũyũ',
  'kj': 'Kuanyama',
  'kk': 'Қазақ тілі (Tiếng Kazakh)',
  'kl': 'Kalaallisut',
  'km': 'ភាសាខ្មែរ (Tiếng Khmer)',
  'kn': 'ಕನ್ನಡ (Tiếng Kannada)',
  'ko': '한국어 (Tiếng Hàn)',
  'kr': 'Kanuri',
  'ks': 'कश्मीरी',
  'ku': 'Kurdî (Tiếng Kurd)',
  'kv': 'Коми кыв',
  'kw': 'Kernewek',
  'ky': 'Кыргыз тили (Tiếng Kyrgyz)',
  'la': 'Latine (Tiếng Latin)',
  'lb': 'Lëtzebuergesch',
  'lg': 'Luganda',
  'li': 'Limburgs',
  'ln': 'Lingála',
  'lo': 'ພາສາລາว (Tiếng Lào)',
  'lt': 'Lietuvių kalba (Tiếng Lithuania)',
  'lu': 'Tshiluba',
  'lv': 'Latviešu valoda (Tiếng Latvian)',
  'mg': 'Malagasy fiteny',
  'mh': 'Kajin M̧ajeļ',
  'mi': 'Te reo Māori',
  'mk': 'Македонски јазик (Tiếng Macedonian)',
  'ml': 'മലയാളം (Tiếng Malayalam)',
  'mn': 'Монгол (Tiếng Mông Cổ)',
  'mr': 'मराठी (Tiếng Marathi)',
  'ms': 'Bahasa Melayu (Tiếng Mã Lai)',
  'mt': 'Malti',
  'my': 'မြန်မာဘာသာ (Tiếng Miến Điện)',
  'na': 'Ekakairũ Naoero',
  'nb': 'Norsk bokmål',
  'nd': 'IsiNdebele',
  'ne': 'नेपाली (Tiếng Nepali)',
  'ng': 'Owambo',
  'nl': 'Nederlands (Tiếng Hà Lan)',
  'nn': 'Norsk nynorsk',
  'no': 'Norsk (Tiếng Na Uy)',
  'nr': 'IsiNdebele',
  'nv': 'Diné bizaad',
  'ny': 'Chi-Chewa',
  'oc': 'Occitan',
  'oj': 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
  'om': 'Afaan Oromoo',
  'or': 'ଓଡ଼ିଆ (Tiếng Oriya)',
  'os': 'Ирон æвзаг',
  'pa': 'ਪੰਜਾਬੀ (Tiếng Punjabi)',
  'pi': 'पाऴि',
  'pl': 'Polski (Tiếng Ba Lan)',
  'ps': 'پښتو (Tiếng Pashto)',
  'pt': 'Português (Tiếng Bồ Đào Nha)',
  'qu': 'Runa Simi',
  'rm': 'Rumantsch grischun',
  'rn': 'Ikirundi',
  'ro': 'Română (Tiếng Romania)',
  'ru': 'Русский (Tiếng Nga)',
  'rw': 'Ikinyarwanda',
  'sa': 'संस्कृतम् (Tiếng Phạn)',
  'sc': 'Sardu',
  'sd': 'सिन्धी',
  'se': 'Davvisámegiella',
  'sg': 'Yângâ tî sängö',
  'si': 'සිංහල (Tiếng Sinhala)',
  'sk': 'Slovenčina (Tiếng Slovak)',
  'sl': 'Slovenščina (Tiếng Slovenian)',
  'sm': 'Gagana fa\'a Samoa',
  'sn': 'ChiShona',
  'so': 'Soomaaliga',
  'sq': 'Shqip (Tiếng Albanian)',
  'sr': 'Српски језик (Tiếng Serbian)',
  'ss': 'SiSwati',
  'st': 'Sesotho',
  'su': 'Basa Sunda',
  'sv': 'Svenska (Tiếng Thụy Điển)',
  'sw': 'Kiswahili',
  'ta': 'தமிழ் (Tiếng Tamil)',
  'te': 'తెలుగు (Tiếng Telugu)',
  'tg': 'Тоҷикӣ (Tiếng Tajik)',
  'th': 'ไทย (Tiếng Thái)',
  'ti': 'ትግርኛ',
  'tk': 'Türkmen',
  'tl': 'Tagalog',
  'tn': 'Setswana',
  'to': 'Faka Tonga',
  'tr': 'Türkçe (Tiếng Thổ Nhĩ Kỳ)',
  'ts': 'Xitsonga',
  'tt': 'Татарча',
  'tw': 'Twi',
  'ty': 'Reo Tahiti',
  'ug': 'Uyƣurqə (Tiếng Uyghur)',
  'uk': 'Українська (Tiếng Ukraina)',
  'ur': 'اردو (Tiếng Urdu)',
  'uz': 'Oʻzbek (Tiếng Uzbek)',
  've': 'Tshivenḓa',
  'vi': 'Tiếng Việt',
  'vo': 'Volapük',
  'wa': 'Walon',
  'wo': 'Wollof',
  'xh': 'IsiXhosa',
  'yi': 'ייִדיש',
  'yo': 'Yorùbá',
  'za': 'Saɯ cueŋƅ',
  'zh': '中文 (Tiếng Trung)',
  'zu': 'IsiZulu',
};

/**
 * Chuyển đổi mã ngôn ngữ thành tên hiển thị bằng danh sách thủ công.
 * @param {string} langCode - Mã ngôn ngữ.
 * @returns {string} Tên hiển thị của ngôn ngữ.
 */
export const getLanguageName = (langCode) => {
  if (!langCode || typeof langCode !== 'string') {
    return "";
  }

  // Xử lý các trường hợp như 'zh-cn', 'en-us' -> chỉ lấy phần đầu 'zh', 'en'
  const baseLangCode = langCode.toLowerCase().split('-')[0];

  return languageLabels[baseLangCode] || langCode.toUpperCase();
};
